language: "en"
early_access: true

reviews:
  request_changes_workflow: true
  high_level_summary: true
  poem: false
  review_status: true
  collapse_walkthrough: false
  sequence_diagrams: true
  profile: "chill"
  path_filters:
    - "!**/*.md"
    - "!**/*.yaml"
    - "!**/*.yml"
    - "!**/*.json"
    - "!**/*.toml"
    - "!**/*.xml"
    - "!**/*.mdc"
    - "!**/*.mdx"
    - "!.cursor/**"
    - "!.git/**"
    - "!.claude/**"
    - "!.vscode/**"
    - "!.taskmaster/**"
    - "!docs/swagger.*"
    - "!**/mock_*.go"
    - "!**/*.pb.go"
    - "!**/*.pb.gw.go"
    - "!**/fixtures/**"
    - "!test/testdata/**"
