services:
  neo4j-test:
    image: neo4j:5-community
    container_name: gograph-neo4j-test
    environment:
      - NEO4J_AUTH=neo4j/testpassword123!
      - NEO4J_PLUGINS=["apoc","graph-data-science"]
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*,gds.*
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_memory_heap_initial__size=512m
      - NEO4J_dbms_memory_heap_max__size=1G
      - NEO4J_dbms_memory_pagecache_size=512m
    ports:
      - "7687:7687"  # Bolt
      - "7474:7474"  # HTTP
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:7474"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s
    volumes:
      - neo4j-test-data:/data
      - neo4j-test-logs:/logs
    networks:
      - gograph-test

networks:
  gograph-test:
    driver: bridge

volumes:
  neo4j-test-data:
  neo4j-test-logs: